/**
 * Reconciliation of the legacy built-in catalog (390 foods, DEC-019) against
 * the canonical points reference — `npm run points:reconcile`.
 *
 * DEC-036: the reference is the ONLY source of the active list. This script
 * runs the same resolver the app uses (`resolveCatalog`) and reports, for
 * every legacy food, how it resolved — explicit link / verified alias / exact
 * name — or that it is HIDDEN (history only), with the closest reference rows
 * as review candidates (never linked automatically). Output:
 *   src/data/points-reference/reconciliation.v1.json (machine-readable)
 *   docs/POINTS_REFERENCE_RECONCILIATION.md          (human-readable, before/after)
 * Nothing in the catalog, the database or any meal history is modified.
 */
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { BUILT_IN_FOODS } from "../../src/lib/food-catalog.ts";
import {
  aliasSafetyIssues,
  buildReferenceIndex,
  BUNDLED_ALIASES,
  resolveCatalog,
  suggestSimilar,
} from "../../src/lib/points-reference/index.ts";
import { formatPortion } from "../../src/lib/points-reference/quantity-parse.ts";
import dataset from "../../src/data/points-reference/reference.v1.runtime.json";
import aliasFile from "../../src/data/points-reference/aliases.v1.json";
import type { ReferenceRuntimeDataset } from "../../src/lib/points-reference/types.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const JSON_PATH = resolve(HERE, "../../src/data/points-reference/reconciliation.v1.json");
const MD_PATH = resolve(HERE, "../../docs/POINTS_REFERENCE_RECONCILIATION.md");

const data = dataset as ReferenceRuntimeDataset;
const index = buildReferenceIndex(data, BUNDLED_ALIASES);
const items = [...index.itemsById.values()];

// "Before" = the DEC-035 behaviour: only exact names linked; every other legacy
// food stayed a card of its own (with the internal model as its points source).
const before = resolveCatalog(buildReferenceIndex(data, []), BUILT_IN_FOODS);
// "After" = DEC-036: verified aliases + hidden legacy rows.
const after = resolveCatalog(index, BUILT_IN_FOODS);

const linked = after.resolutions
  .filter((r) => r.canonicalId)
  .map((r) => {
    const card = after.active.find((f) => f.canonicalId === r.canonicalId)!;
    return {
      foodId: r.food.id,
      foodName: r.food.name,
      category: r.food.category ?? "",
      link: r.link,
      canonicalName: card.name,
      canonicalId: r.canonicalId,
    };
  });

const hidden = after.hidden.map((food) => ({
  foodId: food.id,
  foodName: food.name,
  category: food.category ?? "",
  candidates: suggestSimilar(items, food.name, 3)
    .filter((s) => s.similarity >= 0.34)
    .map((s) => ({
      name: s.item.displayName,
      portion: formatPortion(s.item.portion),
      points: s.item.points,
      similarity: Math.round(s.similarity * 100) / 100,
      issues: aliasSafetyIssues(food.name, s.item.displayName),
    })),
}));

const summary = {
  referenceVersion: data.source.version,
  aliasesVersion: aliasFile.version,
  before: {
    activeCards:
      before.summary.activeReferenceFoods + before.summary.legacyFoods - before.summary.linkedExact,
    referenceFoods: before.summary.activeReferenceFoods,
    legacyCardsShown: before.summary.legacyFoods - before.summary.linkedExact,
    legacyLinkedExact: before.summary.linkedExact,
  },
  after: {
    activeCards: after.active.length,
    referenceFoods: after.summary.activeReferenceFoods,
    coffeeEditorEntry: after.active.length - after.summary.activeReferenceFoods,
    legacyFoods: after.summary.legacyFoods,
    linkedExplicit: after.summary.linkedExplicit,
    linkedAlias: after.summary.linkedAlias,
    linkedExact: after.summary.linkedExact,
    hidden: after.summary.hidden,
    duplicatesCollapsed: after.summary.duplicatesCollapsed,
    verifiedAliases: aliasFile.aliases.length,
  },
};

writeFileSync(JSON_PATH, JSON.stringify({ summary, linked, hidden }, null, 1) + "\n");

const md = [
  "# Reconciliation — legacy catalog × points reference (DEC-036)",
  "",
  `Generated by \`npm run points:reconcile\` from reference **${summary.referenceVersion}** and aliases **${summary.aliasesVersion}**. Read-only: nothing in the catalog, the database or any meal history is changed.`,
  "",
  "## Before / after",
  "",
  "| metric | before (DEC-035) | after (DEC-036) |",
  "| --- | ---: | ---: |",
  `| cards in the active list | ${summary.before.activeCards} | ${summary.after.activeCards} |`,
  `| … reference foods | ${summary.before.referenceFoods} | ${summary.after.referenceFoods} |`,
  `| … legacy catalog cards of their own | ${summary.before.legacyCardsShown} | 0 |`,
  `| … coffee editor entry | 1 | ${summary.after.coffeeEditorEntry} |`,
  `| legacy foods linked by exact name | ${summary.before.legacyLinkedExact} | ${summary.after.linkedExact} |`,
  `| legacy foods linked by verified alias | 0 | ${summary.after.linkedAlias} |`,
  `| legacy foods linked explicitly (personal aliases) | 0 | ${summary.after.linkedExplicit} |`,
  `| legacy foods hidden (history only) | 0 | ${summary.after.hidden} |`,
  `| duplicate cards collapsed onto one reference food | 0 | ${summary.after.duplicatesCollapsed} |`,
  `| verified aliases shipped | 0 | ${summary.after.verifiedAliases} |`,
  "",
  "Rule (DEC-036): a legacy food appears only through a verified link — explicit `reference_group_key`, an alias in `aliases.v1.json`, or an exact normalised name — and then only as the reference food (one card, one canonical id). Everything else is hidden from search, chips, favourites and recents; meal history keeps its snapshots.",
  "",
  "## Linked (shown as the reference food)",
  "",
  "| legacy food | category | via | reference food |",
  "| --- | --- | --- | --- |",
  ...linked.map((l) => `| ${l.foodName} | ${l.category} | ${l.link} | ${l.canonicalName} |`),
  "",
  "## Hidden (no verified link — history only, review candidates NOT linked)",
  "",
  "Candidates list the alias-safety issues the engine raises. To link one, add it to `src/data/points-reference/aliases.v1.json` with a reviewer note (see `docs/POINTS_REFERENCE.md §4`). Rows without candidates need a new reference row from Elena.",
  "",
  "| legacy food | category | candidate | portion | points | similarity | issues |",
  "| --- | --- | --- | --- | ---: | ---: | --- |",
  ...hidden.flatMap((h) =>
    h.candidates.length === 0
      ? [`| ${h.foodName} | ${h.category} | — | | | | no plausible reference row |`]
      : h.candidates.map(
          (c) =>
            `| ${h.foodName} | ${h.category} | ${c.name} | ${c.portion} | ${c.points} | ${c.similarity} | ${c.issues.join(", ") || "—"} |`,
        ),
  ),
  "",
].join("\n");
writeFileSync(MD_PATH, md);

console.log(JSON.stringify(summary, null, 2));
