/**
 * Reconciliation of the existing built-in catalog (390 foods, DEC-019) against
 * the canonical points reference — `npm run points:reconcile`.
 *
 * Exact normalized-name matches are the ONLY automatic links (the app applies
 * the same rule at runtime in `withReference`). Everything else is a review
 * candidate: reported with its similarity, never linked. Output:
 *   src/data/points-reference/reconciliation.v1.json (machine-readable)
 *   docs/POINTS_REFERENCE_RECONCILIATION.md          (human-readable)
 * Nothing in the catalog, the database or any history is modified.
 */
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { BUILT_IN_FOODS } from "../../src/lib/food-catalog.ts";
import { normalizeFoodName } from "../../src/lib/food-normalize.ts";
import {
  aliasSafetyIssues,
  buildReferenceIndex,
  suggestSimilar,
} from "../../src/lib/points-reference/index.ts";
import { formatPortion } from "../../src/lib/points-reference/quantity-parse.ts";
import dataset from "../../src/data/points-reference/reference.v1.json";
import type { ReferenceDataset } from "../../src/lib/points-reference/types.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const JSON_PATH = resolve(HERE, "../../src/data/points-reference/reconciliation.v1.json");
const MD_PATH = resolve(HERE, "../../docs/POINTS_REFERENCE_RECONCILIATION.md");

const index = buildReferenceIndex(dataset as ReferenceDataset);
const items = [...index.itemsById.values()];

interface Link {
  foodId: string;
  foodName: string;
  category: string;
  groupKey: string;
  portions: number;
  points: string;
}
interface Candidate {
  foodId: string;
  foodName: string;
  category: string;
  candidates: Array<{
    name: string;
    portion: string;
    points: number;
    similarity: number;
    issues: string[];
  }>;
}

const linked: Link[] = [];
const review: Candidate[] = [];
const unmatched: Array<{ foodId: string; foodName: string; category: string }> = [];

for (const food of BUILT_IN_FOODS) {
  if (food.kind === "coffee") continue;
  const key = normalizeFoodName(food.name);
  const group = index.groupsByKey.get(key);
  if (group && group.items.length > 0) {
    const pts = group.items.map((i) => i.points);
    linked.push({
      foodId: food.id,
      foodName: food.name,
      category: food.category ?? "",
      groupKey: group.key,
      portions: group.items.length,
      points: pts.length === 1 ? String(pts[0]) : `${Math.min(...pts)}–${Math.max(...pts)}`,
    });
    continue;
  }
  const suggestions = suggestSimilar(items, food.name, 3).filter((s) => s.similarity >= 0.34);
  if (suggestions.length > 0) {
    review.push({
      foodId: food.id,
      foodName: food.name,
      category: food.category ?? "",
      candidates: suggestions.map((s) => ({
        name: s.item.displayName,
        portion: formatPortion(s.item.portion),
        points: s.item.points,
        similarity: Math.round(s.similarity * 100) / 100,
        issues: aliasSafetyIssues(food.name, s.item.displayName),
      })),
    });
  } else {
    unmatched.push({ foodId: food.id, foodName: food.name, category: food.category ?? "" });
  }
}

const summary = {
  referenceVersion: dataset.source.version,
  catalogFoods: BUILT_IN_FOODS.length,
  linkedExact: linked.length,
  reviewCandidates: review.length,
  unmatched: unmatched.length,
  referenceGroupsActive: index.groups.filter((g) => g.items.length > 0).length,
  referenceGroupsClaimedByCatalog: new Set(linked.map((l) => l.groupKey)).size,
};

writeFileSync(JSON_PATH, JSON.stringify({ summary, linked, review, unmatched }, null, 1) + "\n");

const md = [
  "# Reconciliation — built-in catalog × points reference",
  "",
  `Generated by \`npm run points:reconcile\` from reference **${summary.referenceVersion}**. Read-only: nothing in the catalog, the database or any meal history is changed.`,
  "",
  "| metric | value |",
  "| --- | ---: |",
  `| built-in catalog foods | ${summary.catalogFoods} |`,
  `| linked automatically (exact normalized name) | ${summary.linkedExact} |`,
  `| review candidates (similar name, NOT linked) | ${summary.reviewCandidates} |`,
  `| no plausible reference row | ${summary.unmatched} |`,
  `| active reference groups | ${summary.referenceGroupsActive} |`,
  `| … of which claimed by a catalog food | ${summary.referenceGroupsClaimedByCatalog} |`,
  "",
  "Rule: a catalog food is linked only when its normalized name equals a reference name (the same rule the app applies at runtime, `withReference`). A linked food scores through the reference from now on; entries logged before keep their stored snapshot.",
  "",
  "## Linked automatically",
  "",
  "| catalog food | category | reference portions | points |",
  "| --- | --- | ---: | --- |",
  ...linked.map((l) => `| ${l.foodName} | ${l.category} | ${l.portions} | ${l.points} |`),
  "",
  "## Review candidates (not linked — a person decides)",
  "",
  "Each candidate lists the alias-safety issues the engine would raise (`cooking_state_differs`, `light_or_diet_variant_differs`, `recipe_vs_ingredient`). To link one, add a verified alias (see `docs/POINTS_REFERENCE.md`).",
  "",
  "| catalog food | category | candidate | portion | points | similarity | issues |",
  "| --- | --- | --- | --- | ---: | ---: | --- |",
  ...review.flatMap((r) =>
    r.candidates.map(
      (c) =>
        `| ${r.foodName} | ${r.category} | ${c.name} | ${c.portion} | ${c.points} | ${c.similarity} | ${c.issues.join(", ") || "—"} |`,
    ),
  ),
  "",
  "## No plausible reference row",
  "",
  "These keep the internal v2-il model (DEC-034) until a reference row or a confirmed value exists.",
  "",
  ...unmatched.map((u) => `- ${u.foodName} (${u.category})`),
  "",
].join("\n");
writeFileSync(MD_PATH, md);

console.log(summary);
