/**
 * Human-readable import report (docs/POINTS_REFERENCE_IMPORT_REPORT.md),
 * rendered from the same objects the importer writes as JSON. Pure.
 */
import type { ImportReport, ReferenceDataset } from "../../src/lib/points-reference/types.ts";

const REASON_LABEL: Record<string, string> = {
  name_truncated: "שם קטוע במקור (סוגריים לא סגורים / מחבר בסוף)",
  quantity_missing_with_points: "כמות חסרה אף שיש ניקוד",
  quantity_number_without_unit: "כמות מספרית ללא יחידה",
  quantity_unparsed: "כמות שלא ניתן לפענח",
  category_missing: "קטגוריה חסרה",
  conflict_same_name_and_quantity: "סתירה: אותו שם ואותה כמות, ניקוד/קטגוריה שונים",
  benefit_base_food_not_found: "שורת הטבה ללא מאכל בסיס חד-משמעי",
  benefit_row_with_nonzero_points: "שורת הטבה עם ניקוד שאינו 0",
};

export function buildImportReportMd(report: ImportReport, dataset: ReferenceDataset): string {
  const { source } = report;
  const review = dataset.items.filter((i) => i.status === "needs_review");
  const conflicts = dataset.items.filter((i) => i.status === "conflict");
  const deprecated = dataset.items.filter((i) => i.status === "deprecated");
  const row = (i: (typeof dataset.items)[number]) =>
    `| ${i.sourceRow} | ${i.displayName} | ${i.sourceQuantityText ?? "—"} | ${i.points} | ${i.category ?? "—"} | ${i.reviewReasons.map((r) => REASON_LABEL[r] ?? r).join("; ")} |`;
  return [
    "# Import report — points reference (DEC-035)",
    "",
    `Generated by \`npm run points:import\`. Source: \`${source.fileName}\` (sha256 \`${source.sha256}\`), sheet \`${source.sheet}\`, dataset version **${source.version}**.`,
    "",
    "## Counts",
    "",
    "| metric | value |",
    "| --- | ---: |",
    `| rows in sheet | ${report.rowsInSheet} |`,
    `| header rows skipped (repeated \`מאכל או מנה\`) | ${report.headerRows} |`,
    `| blank rows skipped | ${report.blankRows} |`,
    `| non-food rows skipped (title, page marker) | ${report.nonFoodRows} |`,
    `| **food rows imported** | **${report.foodRows}** |`,
    `| distinct source names | ${report.uniqueSourceNames} |`,
    `| distinct search keys (after normalisation) | ${report.uniqueNames} |`,
    `| names with more than one row (variations) | ${report.namesWithVariants} |`,
    `| exact duplicates → \`deprecated\` (merged) | ${report.exactDuplicatesDeprecated} |`,
    `| conflicts → \`conflict\` (rows / groups) | ${report.conflicts} / ${report.conflictGroups.length} |`,
    `| \`needs_review\` | ${report.needsReview} |`,
    `| **\`active\`** | **${report.active}** |`,
    `| benefit rows attached to a base food | ${report.benefitRowsAttached} |`,
    `| benefit rows without a base (review) | ${report.benefitRowsUnattached} |`,
    `| points precision — integer / half / other | ${report.pointsPrecision.integer} / ${report.pointsPrecision.half} / ${report.pointsPrecision.other} |`,
    "",
    "The side table starting at `מה אכלתי` (columns F–H) is never read (rule R01).",
    "",
    "## Cleaning rules applied",
    "",
    "| rule | rows |",
    "| --- | ---: |",
    ...Object.entries(report.cleaningRuleCounts)
      .sort()
      .map(([k, v]) => `| \`${k}\` | ${v} |`),
    "",
    "## Categories (as imported)",
    "",
    "| category | rows |",
    "| --- | ---: |",
    ...Object.entries(report.categories)
      .sort((a, b) => b[1] - a[1])
      .map(([k, v]) => `| ${k} | ${v} |`),
    "",
    "## Conflicts (never offered, never a default, never overwrite user data)",
    "",
    "| row | name | quantity | points | category | reason |",
    "| ---: | --- | --- | ---: | --- | --- |",
    ...conflicts.map(row),
    "",
    "## Needs review",
    "",
    "| reason | rows |",
    "| --- | ---: |",
    ...Object.entries(report.needsReviewByReason)
      .sort((a, b) => b[1] - a[1])
      .map(([k, v]) => `| ${REASON_LABEL[k] ?? k} | ${v} |`),
    "",
    "| row | name | quantity | points | category | reason |",
    "| ---: | --- | --- | ---: | --- | --- |",
    ...review.map(row),
    "",
    "## Deprecated (exact duplicates, merged into the kept row)",
    "",
    "| row | name | quantity | points | category | reason |",
    "| ---: | --- | --- | ---: | --- | --- |",
    ...deprecated.map((i) =>
      row({
        ...i,
        reviewReasons: [
          `duplicate of row ${dataset.items.find((k) => k.id === i.duplicateOf)?.sourceRow}`,
        ],
      }),
    ),
    "",
  ].join("\n");
}
